# Simple workflow for deploying static content to GitHub Pages
name: Run background job and deploy to pages

on:
  schedule:
    - cron: "*/5 * * * *" # every five minutes

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  background-job-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ["3.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run background job
        env:
          BTC_ACCOUNT: ${{ secrets.BTC_ACCOUNT }}
          BTC_PASSWORD: ${{ secrets.BTC_PASSWORD }}
          BUGSNAG_API_KEY: ${{ secrets.BUGSNAG_API_KEY }}
        run: |
          bundle exec bin/run
          mkdir -p build
          cp index.html main.js runner-data.js build/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
